### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Flow512** [Mauler125/detours_r5#28]
how can i find the season 3 build? is there any archives of apex legends builds

**Comment by Code-Leaf-Crash** [comment]
> how can i find the season 3 build? is there any archives of apex legends builds

I have it and im happy to send you it, however the latest release (1.3) doesn't have the r5apex.exe in it, so there's nothing you can actually do. It shows the debug window and then closes.

**Comment by PixieCore** [comment]
Wait for the full release we don't have an stable build yet. I'm gonna close this for now.

**Comment by hax4dazy** [comment]
> I have it and im happy to send you it, however the latest release (1.3) doesn't have the r5apex.exe in it, so there's nothing you can actually do. It shows the debug window and then closes.

Do you mind giving it to me so I can archive it? I should have a discord link on my profile

**Comment by PetarGT** [comment]
@Code-Leaf-Crash Could you send it if its not an issue? I've been trying to find it for ages. My mail is petargt9@gmail.com
