### ISSUE TITLE
any video how to set it up ?

### ISSUE THREAD

**Issue by JamesGordan11** [Mauler125/detours_r5#37]

**Comment by PetarGT** [comment]
i would like to see it too! How do we get the mentioned r5apex.exe that we have to replace the original r5apex.exe with? I want to try this out so badly!

**Comment by hax4dazy** [comment]
Looking at another issue the dev said to "wait ti'll the official release"

**Comment by PixieCore** [comment]
https://discord.com/invite/jqMkUdXrBr Join our discord for further help in this matter. It has all resources there for the mean time.
