### ISSUE TITLE
Could not find global script struct "GRXStoreOffer"

### ISSUE THREAD

**Issue by DevPrestigious** [Mauler125/detours_r5#49]
I'm having this issue right after the server starts loading.
Causes game to crash, any ideas?

![image](https://user-images.githubusercontent.com/66549514/131423652-c7e79ba7-5a6d-4e68-850b-9e3391c71082.png)

**Comment by PixieCore** [comment]
Properly install it.

https://app.gitbook.com/@r5reloaded/s/r5reloaded/
Join the discord for more info and references.
